### ISSUE TITLE
9/5 ~ 9/8 일중 각자 미팅 가능한 날짜 등록!!

### ISSUE THREAD

**Issue by MunSeongUk** [MunSeongUk/StyleIDE#2]
문성욱
화 : 저녁 6시 이후 모두 가능
수 : 불가
목 : 저녁 9시반 이후 모두 가능
금 : 1시 이후 모두 가능

**Comment by seulgi1025** [comment]
박슬기
화 : 불가
수 : 오후 6시까지 가능
목 : 불가
금 : 오후 4시까지 가능

**Comment by hyom** [comment]
전효진
화: 저녁 7시이후 가능
수,목,금: 저녁 6시이전까지 가능(마치는시간)
